//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatesCarSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColumnNamesForRoutes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColumnNamesForRoutes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatesCarSite.Resources.ColumnNamesForRoutes", typeof(ColumnNamesForRoutes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opłata za pasażera.
        /// </summary>
        public static string ChargeForPassenger {
            get {
                return ResourceManager.GetString("ChargeForPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierowca.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacja końcowa.
        /// </summary>
        public static string EndLocation {
            get {
                return ResourceManager.GetString("EndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zużycie paliwa.
        /// </summary>
        public static string FuelUsage {
            get {
                return ResourceManager.GetString("FuelUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opłacona.
        /// </summary>
        public static string IsPaid {
            get {
                return ResourceManager.GetString("IsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie.
        /// </summary>
        public static string IsPaidFalse {
            get {
                return ResourceManager.GetString("IsPaidFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tak.
        /// </summary>
        public static string IsPaidTrue {
            get {
                return ResourceManager.GetString("IsPaidTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacja startowa.
        /// </summary>
        public static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
    }
}
